client:
  auth-server:
    client-id: DEX-466834-000021
    client-secret: 8282a0b2dc2244e8b047527895928972
    user-authorization-uri: https://dev-api.chinadep.com/openapi/oauth/authorize
    access-token-uri: https://dev-api.chinadep.com/openapi/oauth/token
  resources:
    get-uri: https://dev-api.chinadep.com/openapi/v1/task    # 查询列表和交付详情资源接口
    post-uri: https://dev-api.chinadep.com/openapi/v1/deliver  # 提交交付信息反馈和凭证信息反馈接口
    token-head: Authorization

