client:
  auth-server:
    client-id: DEX-466834-000021
    client-secret: 8282a0b2dc2244e8b047527895928972
    user-authorization-uri: http://localhost:8392/dex-ums/oauth/authorize
    access-token-uri: http://localhost:8392/dex-ums/oauth/token
  resources:
    get-uri: http://localhost:8093/daep/openapi/v1/task    # 查询列表和交付详情资源接口
    post-uri: http://10.8.17.90:8081/dex-open-api/openapi/v1/deliver  # 提交交付信息反馈和凭证信息反馈接口
    token-head: Authorization

